// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

import { defineConfig, env } from "prisma/config";

const databaseUrl = `mysql://${env("DB_USER")}:password=${env("DB_PASSWORD")}@${env("DB_HOST")}/${env("DB_NAME")}`
export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: databaseUrl,
  },
});
